name = "Eternal Return"
license = "BSD-2-Clause"
licenselink = "https://github.com/victoriadrake/neofeed-theme/blob/master/LICENSE"
description = "Perhaps this is hell."
homepage = "https://eternalreturn.neocities.org/"
tags = ["personal","timeline","feed","mobile","light","dark","dark mode","customizable","plausible"]
features = ["timeline","neocities","custom css","rss","json"]
min_version = "0.41.0"

[author]
  name = "Euelenlieder"
  homepage = "https://eternalreturn.neocities.org/"
